In [11]:
import pandas as pd
import numpy as np
import sys

In [5]:
a = [1, 2, 3, 4, 5]
b = np.array([1, 2, 3, 4, 5])

In [6]:
print(a)
print(b)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [13]:
print(sys.getsizeof(a))
print(sys.getsizeof(b))

120
124


In [14]:
#Array 1D
d1 = np.array([1, 2, 3])
print(d1)

[1 2 3]


In [15]:
d1.shape

(3,)

In [16]:
d1.ndim

1

In [18]:
d1.dtype

dtype('int32')

In [21]:
#Array 2D
d2 = np.array([[1, 2, 3], [4, 5, 6 ]])
print(d2)

[[1 2 3]
 [4 5 6]]


In [23]:
d2.shape

(2, 3)

In [24]:
d2.ndim

2

In [25]:
d2.dtype

dtype('int32')

In [26]:
#array 3D
d3 = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(d3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [27]:
d3.shape

(2, 2, 2)

In [29]:
d3.ndim

3

In [30]:
d3.dtype

dtype('int32')